### PR TITLE
Bump supported kubernetes from 1.29 to 1.30

### PR DESCRIPTION
**Pull request by takahiro-yamada**
k8s versions are a bit older, but matches with https://github.com/cybozu-go/meows.

- aqua-installer: https://github.com/aquaproj/aqua-installer/releases
- aqua: https://github.com/aquaproj/aqua/releases
- docker/setup-buildx-action: https://github.com/docker/setup-buildx-action/releases
- docker/login-action: https://github.com/docker/login-action/releases
- go: https://github.com/cybozu/neco-containers/blob/3582b8aa8e62a8f8f2a3913c5aa4d8ede78abe89/golang-all/golang-1.23-jammy/TAG
- placemat: https://github.com/cybozu-go/placemat/releases
- controller-tools: https://github.com/kubernetes-sigs/controller-tools/releases
- kustomize: https://github.com/kubernetes-sigs/kustomize/releases
- envtest k8s:
  ```console
  k8s:stage0.cybozu-ne.co-stage0.cybozu-ne.co> ./bin/setup-envtest list | grep v1.30
  (available)  v1.30.3  linux/amd64
  (available)  v1.30.2  linux/amd64
  (available)  v1.30.0  linux/amd64
  ```

### CODE REVIEW

**Comment by zoetrope** [comment]
staticcheck fails due to a different version of go.

setup-go uses the go directive in go.mod as the go version.
https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
https://github.com/actions/setup-go/issues/457

Can you use staticcheck included in cybozu/golang image?
https://github.com/cybozu/neco-containers/blob/3582b8aa8e62a8f8f2a3913c5aa4d8ede78abe89/golang-all/golang-1.23-jammy/Dockerfile#L19

**Review by zoetrope — CHANGES_REQUESTED** [review]
staticcheck fails due to a different version of go.

setup-go uses the go directive in go.mod as the go version.
https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
https://github.com/actions/setup-go/issues/457

Can you use staticcheck included in cybozu/golang image?
https://github.com/cybozu/neco-containers/blob/3582b8aa8e62a8f8f2a3913c5aa4d8ede78abe89/golang-all/golang-1.23-jammy/Dockerfile#L19

**Comment by takahiro-yamada** [comment]
> staticcheck fails due to a different version of go.
> 
> setup-go uses the go directive in go.mod as the go version. https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file [actions/setup-go#457](https://github.com/actions/setup-go/issues/457)
> 
> Can you use staticcheck included in cybozu/golang image? https://github.com/cybozu/neco-containers/blob/3582b8aa8e62a8f8f2a3913c5aa4d8ede78abe89/golang-all/golang-1.23-jammy/Dockerfile#L19

We concluded that it's better to modify the `go` directive in `go.mod` to the latest version instead of following the suggested idea. This change is implemented in https://github.com/cybozu-go/nyamber/pull/59/commits/8d9cb715be23c1987ce91451cd7780391b0d75cc .

**Review by zoetrope — APPROVED** [review]
LGTM

**Pull request merged**
